Server:
   port: 8080
spring:
   application:
       name: running-information-analysis-service
   datasource:
      url: jdbc:mysql://localhost:3306/order_service_db
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update